<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/ProtobufPrinter/specs.proto

namespace ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.Operand.Literal</code>
 */
class Literal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protos.Scalar value = 1;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ProtobufPrinter\ProtobufGenerated\Scalar $value
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufPrinter\ProtobufGenerated\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.Scalar value = 1;</code>
     * @return \ProtobufPrinter\ProtobufGenerated\Scalar|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Generated from protobuf field <code>.protos.Scalar value = 1;</code>
     * @param \ProtobufPrinter\ProtobufGenerated\Scalar $var
     * @return $this
     */
    public function setValue(\ProtobufPrinter\ProtobufGenerated\Scalar|null $var)
    {
        $this->value = $var;

        return $this;
    }

}

