<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/ProtobufPrinter/specs.proto

namespace ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.Operand.Literal</code>
 */
class Literal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protos.ScalarType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $value
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufPrinter\ProtobufGenerated\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.ScalarType type = 1;</code>
     * @return int one of the values in {@see \ProtobufPrinter\ProtobufGenerated\ScalarType}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.protos.ScalarType type = 1;</code>
     * @param int $var one of the values in {@see \ProtobufPrinter\ProtobufGenerated\ScalarType}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \ProtobufPrinter\ProtobufGenerated\ScalarType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->value = $var;

        return $this;
    }

}

