<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/ProtobufPrinter/specs.proto

namespace ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.Operand.Temporary</code>
 */
class Temporary extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>uint32 id = 2;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>optional .protos.Script.Function.Block.Operand.Variable original = 3;</code>
     */
    protected $original = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type int $id
     *     @type \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand\Variable $original
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufPrinter\ProtobufGenerated\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 2;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .protos.Script.Function.Block.Operand.Variable original = 3;</code>
     * @return \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand\Variable|null
     */
    public function getOriginal()
    {
        return $this->original;
    }

    public function hasOriginal()
    {
        return isset($this->original);
    }

    public function clearOriginal()
    {
        unset($this->original);
    }

    /**
     * Generated from protobuf field <code>optional .protos.Script.Function.Block.Operand.Variable original = 3;</code>
     * @param \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand\Variable $var
     * @return $this
     */
    public function setOriginal(\ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand\Variable|null $var)
    {
        $this->original = $var;

        return $this;
    }

}

