<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/ProtobufPrinter/specs.proto

namespace ProtobufPrinter\ProtobufGenerated;

use UnexpectedValueException;

/**
 * Protobuf type <code>protos.OpKind</code>
 */
class OpKind
{
    /**
     * Generated from protobuf enum <code>Phi = 0;</code>
     */
    const Phi = 0;
    /**
     * Generated from protobuf enum <code>Expr_Throw = 2;</code>
     */
    const Expr_Throw = 2;
    /**
     * Generated from protobuf enum <code>Expr_Query = 3;</code>
     */
    const Expr_Query = 3;
    /**
     * Generated from protobuf enum <code>Expr_Stackalloc = 4;</code>
     */
    const Expr_Stackalloc = 4;
    /**
     * Generated from protobuf enum <code>Expr_Sizeof = 5;</code>
     */
    const Expr_Sizeof = 5;
    /**
     * Generated from protobuf enum <code>Expr_IsPattern = 6;</code>
     */
    const Expr_IsPattern = 6;
    /**
     * Generated from protobuf enum <code>Expr_ConstFetch = 7;</code>
     */
    const Expr_ConstFetch = 7;
    /**
     * Generated from protobuf enum <code>Expr_AddressOfExpression = 8;</code>
     */
    const Expr_AddressOfExpression = 8;
    /**
     * Generated from protobuf enum <code>Expr_Range = 9;</code>
     */
    const Expr_Range = 9;
    /**
     * Generated from protobuf enum <code>Expr_IndexExpression = 10;</code>
     */
    const Expr_IndexExpression = 10;
    /**
     * Generated from protobuf enum <code>Expr_Tuple = 11;</code>
     */
    const Expr_Tuple = 11;
    /**
     * Generated from protobuf enum <code>Expr_Parenthesized = 12;</code>
     */
    const Expr_Parenthesized = 12;
    /**
     * Generated from protobuf enum <code>Expr_InterpolatedString = 13;</code>
     */
    const Expr_InterpolatedString = 13;
    /**
     * Generated from protobuf enum <code>Expr_Regex = 14;</code>
     */
    const Expr_Regex = 14;
    /**
     * Generated from protobuf enum <code>Expr_Empty = 15;</code>
     */
    const Expr_Empty = 15;
    /**
     * Generated from protobuf enum <code>Expr_Spread = 16;</code>
     */
    const Expr_Spread = 16;
    /**
     * Generated from protobuf enum <code>Expr_ArrayBinding = 17;</code>
     */
    const Expr_ArrayBinding = 17;
    /**
     * Generated from protobuf enum <code>Expr_ObjectBinding = 18;</code>
     */
    const Expr_ObjectBinding = 18;
    /**
     * Generated from protobuf enum <code>Expr_ClassExpr = 19;</code>
     */
    const Expr_ClassExpr = 19;
    /**
     * Generated from protobuf enum <code>Expr_Continue = 20;</code>
     */
    const Expr_Continue = 20;
    /**
     * Generated from protobuf enum <code>Expr_Delete = 21;</code>
     */
    const Expr_Delete = 21;
    /**
     * Generated from protobuf enum <code>Expr_Void = 22;</code>
     */
    const Expr_Void = 22;
    /**
     * Generated from protobuf enum <code>Expr_Typeof = 23;</code>
     */
    const Expr_Typeof = 23;
    /**
     * Generated from protobuf enum <code>Expr_Star = 24;</code>
     */
    const Expr_Star = 24;
    /**
     * Generated from protobuf enum <code>Expr_Starred = 25;</code>
     */
    const Expr_Starred = 25;
    /**
     * Generated from protobuf enum <code>Expr_StaticCall = 26;</code>
     */
    const Expr_StaticCall = 26;
    /**
     * Generated from protobuf enum <code>Expr_StaticPropertyFetch = 27;</code>
     */
    const Expr_StaticPropertyFetch = 27;
    /**
     * Generated from protobuf enum <code>Expr_Slice = 28;</code>
     */
    const Expr_Slice = 28;
    /**
     * Generated from protobuf enum <code>Expr_KeyVar = 29;</code>
     */
    const Expr_KeyVar = 29;
    /**
     * Generated from protobuf enum <code>Expr_Closure = 30;</code>
     */
    const Expr_Closure = 30;
    /**
     * Generated from protobuf enum <code>Expr_CommandParam = 31;</code>
     */
    const Expr_CommandParam = 31;
    /**
     * Generated from protobuf enum <code>Expr_Switch = 32;</code>
     */
    const Expr_Switch = 32;
    /**
     * Generated from protobuf enum <code>Expr_SuppressNullableWarningExpression = 33;</code>
     */
    const Expr_SuppressNullableWarningExpression = 33;
    /**
     * Generated from protobuf enum <code>Expr_Checked = 34;</code>
     */
    const Expr_Checked = 34;
    /**
     * Generated from protobuf enum <code>Expr_Discard = 35;</code>
     */
    const Expr_Discard = 35;
    /**
     * Generated from protobuf enum <code>Expr_Binding = 36;</code>
     */
    const Expr_Binding = 36;
    /**
     * Generated from protobuf enum <code>Expr_With = 37;</code>
     */
    const Expr_With = 37;
    /**
     * Generated from protobuf enum <code>Expr_Array = 38;</code>
     */
    const Expr_Array = 38;
    /**
     * Generated from protobuf enum <code>Expr_ArrayDimFetch = 39;</code>
     */
    const Expr_ArrayDimFetch = 39;
    /**
     * Generated from protobuf enum <code>Expr_ArrowFunction = 40;</code>
     */
    const Expr_ArrowFunction = 40;
    /**
     * Generated from protobuf enum <code>Expr_Assign = 50;</code>
     */
    const Expr_Assign = 50;
    /**
     * Generated from protobuf enum <code>Expr_AssignRef = 51;</code>
     */
    const Expr_AssignRef = 51;
    /**
     * Generated from protobuf enum <code>Expr_Await = 52;</code>
     */
    const Expr_Await = 52;
    /**
     * Generated from protobuf enum <code>Expr_BitwiseNot = 53;</code>
     */
    const Expr_BitwiseNot = 53;
    /**
     * Generated from protobuf enum <code>Expr_BooleanNot = 54;</code>
     */
    const Expr_BooleanNot = 54;
    /**
     * Generated from protobuf enum <code>Expr_ConcatList = 55;</code>
     */
    const Expr_ConcatList = 55;
    /**
     * Generated from protobuf enum <code>Expr_FuncCall = 56;</code>
     */
    const Expr_FuncCall = 56;
    /**
     * Generated from protobuf enum <code>Expr_InstanceOf = 57;</code>
     */
    const Expr_InstanceOf = 57;
    /**
     * Generated from protobuf enum <code>Expr_MethodCall = 58;</code>
     */
    const Expr_MethodCall = 58;
    /**
     * Generated from protobuf enum <code>Expr_New = 59;</code>
     */
    const Expr_New = 59;
    /**
     * Generated from protobuf enum <code>Expr_Param = 60;</code>
     */
    const Expr_Param = 60;
    /**
     * Generated from protobuf enum <code>Expr_PropertyFetch = 61;</code>
     */
    const Expr_PropertyFetch = 61;
    /**
     * Generated from protobuf enum <code>Expr_Yield = 62;</code>
     */
    const Expr_Yield = 62;
    /**
     * Generated from protobuf enum <code>Expr_Unary = 63;</code>
     */
    const Expr_Unary = 63;
    /**
     * Generated from protobuf enum <code>Expr_UnaryMinus = 64;</code>
     */
    const Expr_UnaryMinus = 64;
    /**
     * Generated from protobuf enum <code>Expr_UnaryPlus = 65;</code>
     */
    const Expr_UnaryPlus = 65;
    /**
     * Generated from protobuf enum <code>Expr_Isset = 66;</code>
     */
    const Expr_Isset = 66;
    /**
     * Generated from protobuf enum <code>Expr_NsFuncCall = 67;</code>
     */
    const Expr_NsFuncCall = 67;
    /**
     * Generated from protobuf enum <code>Expr_Print = 68;</code>
     */
    const Expr_Print = 68;
    /**
     * Generated from protobuf enum <code>Expr_Assertion = 69;</code>
     */
    const Expr_Assertion = 69;
    /**
     * Generated from protobuf enum <code>Expr_VarVar = 70;</code>
     */
    const Expr_VarVar = 70;
    /**
     * Generated from protobuf enum <code>Expr_ClassConstFetch = 71;</code>
     */
    const Expr_ClassConstFetch = 71;
    /**
     * Generated from protobuf enum <code>Expr_Include = 72;</code>
     */
    const Expr_Include = 72;
    /**
     * Generated from protobuf enum <code>Expr_YieldFrom = 73;</code>
     */
    const Expr_YieldFrom = 73;
    /**
     * Generated from protobuf enum <code>Expr_AssignOp_BitwiseAnd = 100;</code>
     */
    const Expr_AssignOp_BitwiseAnd = 100;
    /**
     * Generated from protobuf enum <code>Expr_AssignOp_BitwiseOr = 101;</code>
     */
    const Expr_AssignOp_BitwiseOr = 101;
    /**
     * Generated from protobuf enum <code>Expr_AssignOp_Comma = 102;</code>
     */
    const Expr_AssignOp_Comma = 102;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_As = 200;</code>
     */
    const Expr_BinaryOp_As = 200;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Comma = 201;</code>
     */
    const Expr_BinaryOp_Comma = 201;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_First = 202;</code>
     */
    const Expr_BinaryOp_First = 202;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_In = 203;</code>
     */
    const Expr_BinaryOp_In = 203;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Is = 204;</code>
     */
    const Expr_BinaryOp_Is = 204;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_IsNot = 205;</code>
     */
    const Expr_BinaryOp_IsNot = 205;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_NotIn = 206;</code>
     */
    const Expr_BinaryOp_NotIn = 206;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_BooleanOr = 207;</code>
     */
    const Expr_BinaryOp_BooleanOr = 207;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_BooleanAnd = 208;</code>
     */
    const Expr_BinaryOp_BooleanAnd = 208;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_BitwiseAnd = 209;</code>
     */
    const Expr_BinaryOp_BitwiseAnd = 209;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_BitwiseOr = 210;</code>
     */
    const Expr_BinaryOp_BitwiseOr = 210;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_BitwiseXor = 211;</code>
     */
    const Expr_BinaryOp_BitwiseXor = 211;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_BitwiseNot = 212;</code>
     */
    const Expr_BinaryOp_BitwiseNot = 212;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_BitwiseNotAnd = 213;</code>
     */
    const Expr_BinaryOp_BitwiseNotAnd = 213;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_UnsignedRightShift = 214;</code>
     */
    const Expr_BinaryOp_UnsignedRightShift = 214;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Coalesce = 215;</code>
     */
    const Expr_BinaryOp_Coalesce = 215;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Concat = 216;</code>
     */
    const Expr_BinaryOp_Concat = 216;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Div = 217;</code>
     */
    const Expr_BinaryOp_Div = 217;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Equal = 218;</code>
     */
    const Expr_BinaryOp_Equal = 218;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Greater = 219;</code>
     */
    const Expr_BinaryOp_Greater = 219;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_GreaterOrEqual = 220;</code>
     */
    const Expr_BinaryOp_GreaterOrEqual = 220;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Identical = 221;</code>
     */
    const Expr_BinaryOp_Identical = 221;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_LogicalXor = 222;</code>
     */
    const Expr_BinaryOp_LogicalXor = 222;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Minus = 223;</code>
     */
    const Expr_BinaryOp_Minus = 223;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Mod = 224;</code>
     */
    const Expr_BinaryOp_Mod = 224;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Mul = 225;</code>
     */
    const Expr_BinaryOp_Mul = 225;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_NotEqual = 226;</code>
     */
    const Expr_BinaryOp_NotEqual = 226;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_NotIdentical = 227;</code>
     */
    const Expr_BinaryOp_NotIdentical = 227;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Plus = 228;</code>
     */
    const Expr_BinaryOp_Plus = 228;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Pow = 229;</code>
     */
    const Expr_BinaryOp_Pow = 229;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_ShiftLeft = 230;</code>
     */
    const Expr_BinaryOp_ShiftLeft = 230;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_ShiftRight = 231;</code>
     */
    const Expr_BinaryOp_ShiftRight = 231;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Smaller = 232;</code>
     */
    const Expr_BinaryOp_Smaller = 232;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_SmallerOrEqual = 233;</code>
     */
    const Expr_BinaryOp_SmallerOrEqual = 233;
    /**
     * Generated from protobuf enum <code>Expr_BinaryOp_Spaceship = 234;</code>
     */
    const Expr_BinaryOp_Spaceship = 234;
    /**
     * Generated from protobuf enum <code>Expr_Cast_Array = 300;</code>
     */
    const Expr_Cast_Array = 300;
    /**
     * Generated from protobuf enum <code>Expr_Cast_Bool = 301;</code>
     */
    const Expr_Cast_Bool = 301;
    /**
     * Generated from protobuf enum <code>Expr_Cast_Double = 302;</code>
     */
    const Expr_Cast_Double = 302;
    /**
     * Generated from protobuf enum <code>Expr_Cast_Int = 303;</code>
     */
    const Expr_Cast_Int = 303;
    /**
     * Generated from protobuf enum <code>Expr_Cast_Object = 304;</code>
     */
    const Expr_Cast_Object = 304;
    /**
     * Generated from protobuf enum <code>Expr_Cast_String = 305;</code>
     */
    const Expr_Cast_String = 305;
    /**
     * Generated from protobuf enum <code>Expr_Cast_Type = 306;</code>
     */
    const Expr_Cast_Type = 306;
    /**
     * Generated from protobuf enum <code>Expr_Cast_Unset = 307;</code>
     */
    const Expr_Cast_Unset = 307;
    /**
     * Generated from protobuf enum <code>Iterator_Key = 401;</code>
     */
    const Iterator_Key = 401;
    /**
     * Generated from protobuf enum <code>Iterator_Next = 402;</code>
     */
    const Iterator_Next = 402;
    /**
     * Generated from protobuf enum <code>Iterator_Reset = 403;</code>
     */
    const Iterator_Reset = 403;
    /**
     * Generated from protobuf enum <code>Iterator_Valid = 404;</code>
     */
    const Iterator_Valid = 404;
    /**
     * Generated from protobuf enum <code>Iterator_Value = 405;</code>
     */
    const Iterator_Value = 405;
    /**
     * Generated from protobuf enum <code>Stmt_Class = 500;</code>
     */
    const Stmt_Class = 500;
    /**
     * Generated from protobuf enum <code>Stmt_ClassMethod = 501;</code>
     */
    const Stmt_ClassMethod = 501;
    /**
     * Generated from protobuf enum <code>Stmt_Function = 502;</code>
     */
    const Stmt_Function = 502;
    /**
     * Generated from protobuf enum <code>Stmt_Import = 503;</code>
     */
    const Stmt_Import = 503;
    /**
     * Generated from protobuf enum <code>Stmt_Jump = 504;</code>
     */
    const Stmt_Jump = 504;
    /**
     * Generated from protobuf enum <code>Stmt_JumpIf = 505;</code>
     */
    const Stmt_JumpIf = 505;
    /**
     * Generated from protobuf enum <code>Stmt_Property = 507;</code>
     */
    const Stmt_Property = 507;
    /**
     * Generated from protobuf enum <code>Stmt_Switch = 508;</code>
     */
    const Stmt_Switch = 508;
    /**
     * Generated from protobuf enum <code>Stmt_Try = 509;</code>
     */
    const Stmt_Try = 509;
    /**
     * Generated from protobuf enum <code>Stmt_VarDeclaration = 510;</code>
     */
    const Stmt_VarDeclaration = 510;
    /**
     * Generated from protobuf enum <code>Stmt_With = 511;</code>
     */
    const Stmt_With = 511;
    /**
     * Generated from protobuf enum <code>Stmt_Yield = 512;</code>
     */
    const Stmt_Yield = 512;
    /**
     * Generated from protobuf enum <code>Stmt_Break = 513;</code>
     */
    const Stmt_Break = 513;
    /**
     * Generated from protobuf enum <code>Stmt_Interface = 514;</code>
     */
    const Stmt_Interface = 514;
    /**
     * Generated from protobuf enum <code>Stmt_Export = 515;</code>
     */
    const Stmt_Export = 515;
    /**
     * Generated from protobuf enum <code>Stmt_Namespace = 516;</code>
     */
    const Stmt_Namespace = 516;
    /**
     * Generated from protobuf enum <code>Stmt_Use = 517;</code>
     */
    const Stmt_Use = 517;
    /**
     * Generated from protobuf enum <code>Stmt_Trait = 518;</code>
     */
    const Stmt_Trait = 518;
    /**
     * Generated from protobuf enum <code>Stmt_TraitUse = 519;</code>
     */
    const Stmt_TraitUse = 519;
    /**
     * Generated from protobuf enum <code>Stmt_MatchTable = 520;</code>
     */
    const Stmt_MatchTable = 520;
    /**
     * Generated from protobuf enum <code>Terminal_Exit = 600;</code>
     */
    const Terminal_Exit = 600;
    /**
     * Generated from protobuf enum <code>Terminal_Return = 601;</code>
     */
    const Terminal_Return = 601;
    /**
     * Generated from protobuf enum <code>Terminal_Throw = 602;</code>
     */
    const Terminal_Throw = 602;
    /**
     * Generated from protobuf enum <code>Terminal_GlobalVar = 603;</code>
     */
    const Terminal_GlobalVar = 603;
    /**
     * Generated from protobuf enum <code>Terminal_MatchError = 604;</code>
     */
    const Terminal_MatchError = 604;
    /**
     * Generated from protobuf enum <code>Terminal_StaticVar = 605;</code>
     */
    const Terminal_StaticVar = 605;
    /**
     * Generated from protobuf enum <code>Terminal_Const = 606;</code>
     */
    const Terminal_Const = 606;
    /**
     * Generated from protobuf enum <code>Terminal_Echo = 607;</code>
     */
    const Terminal_Echo = 607;

    private static $valueToName = [
        self::Phi => 'Phi',
        self::Expr_Throw => 'Expr_Throw',
        self::Expr_Query => 'Expr_Query',
        self::Expr_Stackalloc => 'Expr_Stackalloc',
        self::Expr_Sizeof => 'Expr_Sizeof',
        self::Expr_IsPattern => 'Expr_IsPattern',
        self::Expr_ConstFetch => 'Expr_ConstFetch',
        self::Expr_AddressOfExpression => 'Expr_AddressOfExpression',
        self::Expr_Range => 'Expr_Range',
        self::Expr_IndexExpression => 'Expr_IndexExpression',
        self::Expr_Tuple => 'Expr_Tuple',
        self::Expr_Parenthesized => 'Expr_Parenthesized',
        self::Expr_InterpolatedString => 'Expr_InterpolatedString',
        self::Expr_Regex => 'Expr_Regex',
        self::Expr_Empty => 'Expr_Empty',
        self::Expr_Spread => 'Expr_Spread',
        self::Expr_ArrayBinding => 'Expr_ArrayBinding',
        self::Expr_ObjectBinding => 'Expr_ObjectBinding',
        self::Expr_ClassExpr => 'Expr_ClassExpr',
        self::Expr_Continue => 'Expr_Continue',
        self::Expr_Delete => 'Expr_Delete',
        self::Expr_Void => 'Expr_Void',
        self::Expr_Typeof => 'Expr_Typeof',
        self::Expr_Star => 'Expr_Star',
        self::Expr_Starred => 'Expr_Starred',
        self::Expr_StaticCall => 'Expr_StaticCall',
        self::Expr_StaticPropertyFetch => 'Expr_StaticPropertyFetch',
        self::Expr_Slice => 'Expr_Slice',
        self::Expr_KeyVar => 'Expr_KeyVar',
        self::Expr_Closure => 'Expr_Closure',
        self::Expr_CommandParam => 'Expr_CommandParam',
        self::Expr_Switch => 'Expr_Switch',
        self::Expr_SuppressNullableWarningExpression => 'Expr_SuppressNullableWarningExpression',
        self::Expr_Checked => 'Expr_Checked',
        self::Expr_Discard => 'Expr_Discard',
        self::Expr_Binding => 'Expr_Binding',
        self::Expr_With => 'Expr_With',
        self::Expr_Array => 'Expr_Array',
        self::Expr_ArrayDimFetch => 'Expr_ArrayDimFetch',
        self::Expr_ArrowFunction => 'Expr_ArrowFunction',
        self::Expr_Assign => 'Expr_Assign',
        self::Expr_AssignRef => 'Expr_AssignRef',
        self::Expr_Await => 'Expr_Await',
        self::Expr_BitwiseNot => 'Expr_BitwiseNot',
        self::Expr_BooleanNot => 'Expr_BooleanNot',
        self::Expr_ConcatList => 'Expr_ConcatList',
        self::Expr_FuncCall => 'Expr_FuncCall',
        self::Expr_InstanceOf => 'Expr_InstanceOf',
        self::Expr_MethodCall => 'Expr_MethodCall',
        self::Expr_New => 'Expr_New',
        self::Expr_Param => 'Expr_Param',
        self::Expr_PropertyFetch => 'Expr_PropertyFetch',
        self::Expr_Yield => 'Expr_Yield',
        self::Expr_Unary => 'Expr_Unary',
        self::Expr_UnaryMinus => 'Expr_UnaryMinus',
        self::Expr_UnaryPlus => 'Expr_UnaryPlus',
        self::Expr_Isset => 'Expr_Isset',
        self::Expr_NsFuncCall => 'Expr_NsFuncCall',
        self::Expr_Print => 'Expr_Print',
        self::Expr_Assertion => 'Expr_Assertion',
        self::Expr_VarVar => 'Expr_VarVar',
        self::Expr_ClassConstFetch => 'Expr_ClassConstFetch',
        self::Expr_Include => 'Expr_Include',
        self::Expr_YieldFrom => 'Expr_YieldFrom',
        self::Expr_AssignOp_BitwiseAnd => 'Expr_AssignOp_BitwiseAnd',
        self::Expr_AssignOp_BitwiseOr => 'Expr_AssignOp_BitwiseOr',
        self::Expr_AssignOp_Comma => 'Expr_AssignOp_Comma',
        self::Expr_BinaryOp_As => 'Expr_BinaryOp_As',
        self::Expr_BinaryOp_Comma => 'Expr_BinaryOp_Comma',
        self::Expr_BinaryOp_First => 'Expr_BinaryOp_First',
        self::Expr_BinaryOp_In => 'Expr_BinaryOp_In',
        self::Expr_BinaryOp_Is => 'Expr_BinaryOp_Is',
        self::Expr_BinaryOp_IsNot => 'Expr_BinaryOp_IsNot',
        self::Expr_BinaryOp_NotIn => 'Expr_BinaryOp_NotIn',
        self::Expr_BinaryOp_BooleanOr => 'Expr_BinaryOp_BooleanOr',
        self::Expr_BinaryOp_BooleanAnd => 'Expr_BinaryOp_BooleanAnd',
        self::Expr_BinaryOp_BitwiseAnd => 'Expr_BinaryOp_BitwiseAnd',
        self::Expr_BinaryOp_BitwiseOr => 'Expr_BinaryOp_BitwiseOr',
        self::Expr_BinaryOp_BitwiseXor => 'Expr_BinaryOp_BitwiseXor',
        self::Expr_BinaryOp_BitwiseNot => 'Expr_BinaryOp_BitwiseNot',
        self::Expr_BinaryOp_BitwiseNotAnd => 'Expr_BinaryOp_BitwiseNotAnd',
        self::Expr_BinaryOp_UnsignedRightShift => 'Expr_BinaryOp_UnsignedRightShift',
        self::Expr_BinaryOp_Coalesce => 'Expr_BinaryOp_Coalesce',
        self::Expr_BinaryOp_Concat => 'Expr_BinaryOp_Concat',
        self::Expr_BinaryOp_Div => 'Expr_BinaryOp_Div',
        self::Expr_BinaryOp_Equal => 'Expr_BinaryOp_Equal',
        self::Expr_BinaryOp_Greater => 'Expr_BinaryOp_Greater',
        self::Expr_BinaryOp_GreaterOrEqual => 'Expr_BinaryOp_GreaterOrEqual',
        self::Expr_BinaryOp_Identical => 'Expr_BinaryOp_Identical',
        self::Expr_BinaryOp_LogicalXor => 'Expr_BinaryOp_LogicalXor',
        self::Expr_BinaryOp_Minus => 'Expr_BinaryOp_Minus',
        self::Expr_BinaryOp_Mod => 'Expr_BinaryOp_Mod',
        self::Expr_BinaryOp_Mul => 'Expr_BinaryOp_Mul',
        self::Expr_BinaryOp_NotEqual => 'Expr_BinaryOp_NotEqual',
        self::Expr_BinaryOp_NotIdentical => 'Expr_BinaryOp_NotIdentical',
        self::Expr_BinaryOp_Plus => 'Expr_BinaryOp_Plus',
        self::Expr_BinaryOp_Pow => 'Expr_BinaryOp_Pow',
        self::Expr_BinaryOp_ShiftLeft => 'Expr_BinaryOp_ShiftLeft',
        self::Expr_BinaryOp_ShiftRight => 'Expr_BinaryOp_ShiftRight',
        self::Expr_BinaryOp_Smaller => 'Expr_BinaryOp_Smaller',
        self::Expr_BinaryOp_SmallerOrEqual => 'Expr_BinaryOp_SmallerOrEqual',
        self::Expr_BinaryOp_Spaceship => 'Expr_BinaryOp_Spaceship',
        self::Expr_Cast_Array => 'Expr_Cast_Array',
        self::Expr_Cast_Bool => 'Expr_Cast_Bool',
        self::Expr_Cast_Double => 'Expr_Cast_Double',
        self::Expr_Cast_Int => 'Expr_Cast_Int',
        self::Expr_Cast_Object => 'Expr_Cast_Object',
        self::Expr_Cast_String => 'Expr_Cast_String',
        self::Expr_Cast_Type => 'Expr_Cast_Type',
        self::Expr_Cast_Unset => 'Expr_Cast_Unset',
        self::Iterator_Key => 'Iterator_Key',
        self::Iterator_Next => 'Iterator_Next',
        self::Iterator_Reset => 'Iterator_Reset',
        self::Iterator_Valid => 'Iterator_Valid',
        self::Iterator_Value => 'Iterator_Value',
        self::Stmt_Class => 'Stmt_Class',
        self::Stmt_ClassMethod => 'Stmt_ClassMethod',
        self::Stmt_Function => 'Stmt_Function',
        self::Stmt_Import => 'Stmt_Import',
        self::Stmt_Jump => 'Stmt_Jump',
        self::Stmt_JumpIf => 'Stmt_JumpIf',
        self::Stmt_Property => 'Stmt_Property',
        self::Stmt_Switch => 'Stmt_Switch',
        self::Stmt_Try => 'Stmt_Try',
        self::Stmt_VarDeclaration => 'Stmt_VarDeclaration',
        self::Stmt_With => 'Stmt_With',
        self::Stmt_Yield => 'Stmt_Yield',
        self::Stmt_Break => 'Stmt_Break',
        self::Stmt_Interface => 'Stmt_Interface',
        self::Stmt_Export => 'Stmt_Export',
        self::Stmt_Namespace => 'Stmt_Namespace',
        self::Stmt_Use => 'Stmt_Use',
        self::Stmt_Trait => 'Stmt_Trait',
        self::Stmt_TraitUse => 'Stmt_TraitUse',
        self::Stmt_MatchTable => 'Stmt_MatchTable',
        self::Terminal_Exit => 'Terminal_Exit',
        self::Terminal_Return => 'Terminal_Return',
        self::Terminal_Throw => 'Terminal_Throw',
        self::Terminal_GlobalVar => 'Terminal_GlobalVar',
        self::Terminal_MatchError => 'Terminal_MatchError',
        self::Terminal_StaticVar => 'Terminal_StaticVar',
        self::Terminal_Const => 'Terminal_Const',
        self::Terminal_Echo => 'Terminal_Echo',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

