<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/ProtobufPrinter/specs.proto

namespace ProtobufPrinter\ProtobufGenerated;

use UnexpectedValueException;

/**
 * Protobuf type <code>protos.ScalarType</code>
 */
class ScalarType
{
    /**
     * Generated from protobuf enum <code>String = 0;</code>
     */
    const String = 0;
    /**
     * Generated from protobuf enum <code>Float = 1;</code>
     */
    const Float = 1;
    /**
     * Generated from protobuf enum <code>Int = 2;</code>
     */
    const Int = 2;
    /**
     * Generated from protobuf enum <code>Bool = 3;</code>
     */
    const Bool = 3;

    private static $valueToName = [
        self::String => 'String',
        self::Float => 'Float',
        self::Int => 'Int',
        self::Bool => 'Bool',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

