<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/ProtobufPrinter/specs.proto

namespace ProtobufPrinter\ProtobufGenerated\Script;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protos.Script.Function</code>
 */
class PBFunction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block blocks = 1;</code>
     */
    private $blocks;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional string class = 3;</code>
     */
    protected $class = null;
    /**
     * Generated from protobuf field <code>string returnType = 4;</code>
     */
    protected $returnType = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block[] $blocks
     *     @type string $name
     *     @type string $class
     *     @type string $returnType
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufPrinter\ProtobufGenerated\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block blocks = 1;</code>
     * @return RepeatedField<\ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block>
     */
    public function getBlocks()
    {
        return $this->blocks;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block blocks = 1;</code>
     * @param \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block[] $var
     * @return $this
     */
    public function setBlocks(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block::class);
        $this->blocks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string class = 3;</code>
     * @return string
     */
    public function getClass()
    {
        return isset($this->class) ? $this->class : '';
    }

    public function hasClass()
    {
        return isset($this->class);
    }

    public function clearClass()
    {
        unset($this->class);
    }

    /**
     * Generated from protobuf field <code>optional string class = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClass(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->class = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string returnType = 4;</code>
     * @return string
     */
    public function getReturnType()
    {
        return $this->returnType;
    }

    /**
     * Generated from protobuf field <code>string returnType = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setReturnType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->returnType = $var;

        return $this;
    }

}

