<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/ProtobufPrinter/specs.proto

namespace ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.CatchTarget</code>
 */
class CatchTarget extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.OneOperand var = 2;</code>
     */
    protected $var = null;
    /**
     * Generated from protobuf field <code>uint32 blockId = 3;</code>
     */
    protected $blockId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand\OneOperand $var
     *     @type int $blockId
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufPrinter\ProtobufGenerated\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.OneOperand var = 2;</code>
     * @return \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand\OneOperand|null
     */
    public function getVar()
    {
        return $this->var;
    }

    public function hasVar()
    {
        return isset($this->var);
    }

    public function clearVar()
    {
        unset($this->var);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.OneOperand var = 2;</code>
     * @param \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand\OneOperand $var
     * @return $this
     */
    public function setVar(\ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Operand\OneOperand|null $var)
    {
        $this->var = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 blockId = 3;</code>
     * @return int
     */
    public function getBlockId()
    {
        return $this->blockId;
    }

    /**
     * Generated from protobuf field <code>uint32 blockId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->blockId = $var;

        return $this;
    }

}

