<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/ProtobufPrinter/specs.proto

namespace ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.Op</code>
 */
class Op extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protos.OpKind kind = 1;</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Op.MapLabel label = 2;</code>
     */
    protected $label = null;
    /**
     * Generated from protobuf field <code>map<string, uint32> childBlocks = 3;</code>
     */
    private $childBlocks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $kind
     *     @type \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Op\MapLabel $label
     *     @type array|\Google\Protobuf\Internal\MapField $childBlocks
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufPrinter\ProtobufGenerated\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.OpKind kind = 1;</code>
     * @return int one of the values in {@see \ProtobufPrinter\ProtobufGenerated\OpKind}
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.protos.OpKind kind = 1;</code>
     * @param int $var one of the values in {@see \ProtobufPrinter\ProtobufGenerated\OpKind}
     * @return $this
     */
    public function setKind(int $var)
    {
        GPBUtil::checkEnum($var, \ProtobufPrinter\ProtobufGenerated\OpKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Op.MapLabel label = 2;</code>
     * @return \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Op\MapLabel|null
     */
    public function getLabel()
    {
        return $this->label;
    }

    public function hasLabel()
    {
        return isset($this->label);
    }

    public function clearLabel()
    {
        unset($this->label);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Op.MapLabel label = 2;</code>
     * @param \ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Op\MapLabel $var
     * @return $this
     */
    public function setLabel(\ProtobufPrinter\ProtobufGenerated\Script\PBFunction\Block\Op\MapLabel|null $var)
    {
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, uint32> childBlocks = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getChildBlocks()
    {
        return $this->childBlocks;
    }

    /**
     * Generated from protobuf field <code>map<string, uint32> childBlocks = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setChildBlocks(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->childBlocks = $arr;

        return $this;
    }

}

